services:
  - type: web
    name: laravel-api
    env: docker
    plan: free
    rootDir: back-end
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: base64:9Zklg3chLhJJ+Bu8VZz6xMSVp+jt4oVZvXwV54Drtx0= 
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: localhost
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: Encourses
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        value: 123456
