services:
  - type: web
    name: laravel-api
    env: docker
    plan: free
    rootDir: back-end
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: base64:9Zklg3chLhJJ+Bu8VZz6xMSVp+jt4oVZvXwV54Drtx0= 
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d1hqadruibrs73fnrnug-a.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: encourses
      - key: DB_USERNAME
        value: encourses_user
      - key: DB_PASSWORD
        value: 1DjyXUsc4FE9ScWI0iEo2m1e8e6o2xr9
